### ISSUE TITLE
Python code goes against PEP-8

### ISSUE THREAD

**Issue by j4cobgarby** [mally1mk/space-avoiders#1]
# Blank lines

First of all, there's a ridiculous amount of blank lines just randomly scattered around - why? For example, look at this part of your code:

```python
ll_brown=(238,221,130)

block_color =(210,105,30) #(53,115,255)













font = pygame.font.SysFont('SquareFont', 15)



 
car_width = 35.5


 
gameDisplay = pygame.display.set_mode((display_width,display_height))



clock = pygame.time.Clock()




 
shipimg = pygame.image.load('galgadaship.png')
```
According to PEP-8, you're supposed to surround top-level functions and classes with two blank lines, and class methods with one blank line. As far as I can see you're not using classes (which I would highly suggest you do,) so perhaps look into this.

PEP-8 also specifies that you should

> Use blank lines in functions, **sparingly**, to indicate **logical sections**.

Fair enough with _some_ of the blank lines in between variables defined at the top of the script, but in most cases you need to have a look at PEP-8.

# Variable naming

When you name variables, make sure they're named so that anyone looking at your code will know _exactly_ what they're for, if possible. The colours are named fairly well, but I wonder about variables related to "things". What, in your game, is a "thing"? Because you have variables named like `thingCount`, `thing_speed`, and then, to make people even more confused you go and make a `thing_speed2`?

I also noticed that you use many different variable naming conventions, for example [lowerCamelCase](http://wiki.c2.com/?LowerCamelCase), and also [https://en.wikipedia.org/wiki/Snake_case](snake_case). I'd suggest thoroughly reading [https://www.python.org/dev/peps/pep-0008/#prescriptive-naming-conventions](this).

# Full PEP-8 evaluation.

I don't have time to give detailed information about all of the provlems, but here's a full evaluation of how your script matches the PEP-8 specification, generated [here.](http://pep8online.com).

**Edit: ** PEP-8 evaluation removed as it was too long. Go to the previous link and copy your code in to have it generated.

**Comment by mally1mk** [comment]
thanks for the tips i am releasing an update somewhere next week and if you have more tips feel free to leave them because this is my first game in python and i dont really now what to  do 

bye   (:

**Comment by mally1mk** [comment]
and can you give an example of a class please

**Comment by j4cobgarby** [comment]
Okay - for a definition have a look [here](https://en.wikipedia.org/wiki/Class_(computer_programming)). Here's an example, in Python, for an `Asteroid` class.

```python
class Asteroid:
    def __init__(self, position, size):
        self.position = position
        self.size = size
    def draw(self):
        # Some logic here to draw the asteroid. Since you're passing `self` as a parameter, you
        # can access the position and size like this:
        print(self.position, self.size)

# And you create an instance like this

# An asteroid at the position 52, 26, with a size of 24
asteroid1 = Asteroid([52, 26], 24)

# And another one at a different position and size
asteroid2 = Asteroid([29, 98], 11)

# Then of course you can call the class functions (or, methods) like so:
asteroid1.draw()
asteroid2.draw()
```

Also notice that I'm never actually giving the parameter `self`. This is because Python passes this parameter into the function itself. If it isn't self-explanatory, self is basically a pointer to the actual class which allows you to access its properties and methods.

## Where would you use classes?

Well, in a game, there a lot of different uses. Mainly, for any sort of object of which there will be many instances, e.g.
 - The player
 - Monsters
 - Trees

**Comment by mally1mk** [comment]
Thanks you i Will try to code some classes bye

Op 6 aug. 2017 3:13 p.m. schreef "Jacob Garby" <notifications@github.com>:

**Comment by j4cobgarby** [comment]
Okay - good luck

**Comment by mally1mk** [comment]
Thanks

Op 6 aug. 2017 3:17 p.m. schreef "Jacob Garby" <notifications@github.com>:

**Comment by mally1mk** [comment]
this is what i have now but how do i detect collision

import pygame
import random

# it is better to have an extra variable, than an extremely long line.
displayw=800
displayh=700

white=(255,255,255)
black = (0,0,0)
white = (255,255,255)
limegreen=(50,205,50)
red1=(250,128,114)
red2=(255,160,122)
red = (255,0,0)
bright_red=(220,20,60)
bright_green = (0,255,0)
bright_green = (0,255,0)
green = (0,200,0)
yellow=(153,153,0)
black = (0,0,0)
light_brown=(218,165,32)
iii_brown=(184,134,11)
ll_brown=(238,221,130)

bg=pygame.image.load('galgadab.png')
clock = pygame.time.Clock()
gameDisplay=pygame.display.set_mode((displayw,displayh))





class Spaceship(object):  # represents the spaceship, not the game
    def __init__(self):
        #""" The constructor of the class """
        self.image = pygame.image.load('galgadaship.png')
        # the spaceship's position
        self.x = (displayw * 0.45)
        self.y = (displayh * 0.8)



    def handle_keys(self):
        #""" Handles Keys """
        key = pygame.key.get_pressed()
        dist = 5 # distance moved in 1 frame, try changing it to 5
        if key[pygame.K_RIGHT]: # right key
            self.x += dist # move right
        elif key[pygame.K_LEFT]: # left key
            self.x -= dist # move left

    def draw(self, surface):
        #""" Draw on surface """
        # blit yourself at your current position
        surface.blit(self.image, (self.x, self.y))


class Asteroid(object):
    def __init__(self):
        self.image=pygame.image.load('rock.png').convert_alpha()
        self.x=0
        self.y=0

    def astrfall(self):
        self.y+=7
        if self.y > displayh:
            self.y = -100
            self.x = random.randrange(0,displayw)



    def draw(self, surface):
        """ Draw on surface """
        # blit yourself at your current position
        surface.blit(self.image, (self.x, self.y))



def BG():
    gameDisplay.fill(white)
    gameDisplay.blit(bg,(0,0))




pygame.init()#initiate pygame
screen = pygame.display.set_mode((displayw, displayh)) #config
window(screen)
spaceship = Spaceship() # create an instance
rock=Asteroid() #create an instance



running = True
while running:
    # handle every event since the last frame.
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
            pygame.quit()
            quit()


   # if hit:
       # spaceship.image.fill((255, 255, 255))
    spaceship.handle_keys() # handle the keys
    rock.astrfall()
    rock.draw(screen)#draw the asteroid(rock)
    spaceship.draw(screen) # draw the spaceship to the screen
    pygame.display.update() # update the screen
    BG()
    clock.tick(60)

2017-08-06 15:18 GMT+02:00 Mally1 Ketel <mally1.mk@gmail.com>:

**Comment by j4cobgarby** [comment]
I can't tell you how to detect collisions because I don't completely know how your game works, but have a look at [AABB](https://en.wikipedia.org/wiki/Minimum_bounding_box#Axis-aligned_minimum_bounding_box). Basically an axis aligned bounding box is a square, with no rotation, which encapsulates an object whilst being the smallest possible size to do so.

A simple way of detecting collisions would be to generate AABBs for the spaceship and for each asteroid, and then checking if any of the bounding boxes overlap. You can find code to do this with a simple Google search, but I'd suggest having a look at [this article on the MDN.](https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection#Axis-Aligned_Bounding_Box)

**Comment by mally1mk** [comment]
Op 11 aug. 2017 19:14 schreef "Jacob Garby" <notifications@github.com>:

**Comment by mally1mk** [comment]
i published a new game called asteroid invasion and someone sad that you
can,t save the highscore for a new launch can you help me out
here is the URL for my code(https://github.com/mally1mk/asteroid-invasion)

**Comment by j4cobgarby** [comment]
I'd happily help, but I don't know the details of your problem.

When the saving doesn't work:
 - What operating system is it running on?
 - Is there an error message? If so, what is it?
 - What version of Python, exactly?

**Comment by j4cobgarby** [comment]
One thing I noticed, however, is that when you (try to) get the absolute path of the Python file being run, you use 
```python
os.path.dirname(__file__)
```
when it _might_ work better to use
```python
os.path.dirname(os.path.abspath(__file__))
```
I can't test this, however, since I can't manage to install Pygame on my computer.

**Comment by mally1mk** [comment]
Windows 10
No error message
3.6.1

Op 13 aug. 2017 19:32 schreef "Jacob Garby" <notifications@github.com>:
